server:
  port: 8888

spring:
  profiles:
    active: native
  application:
    name: config-service
  cloud:
    config:
      server:
        git:
          uri:

health:
  config:
    enabled: false

logging:
  level:
    web: debug
