server:
  port: 8888

spring:
  application:
    name: config-service
  cloud:
    config:
      server:
        git:
          uri: https://github.com/UMdz/UM.tesoreria.config-service
          default-label: main
          search-paths: config-data

logging:
  level:
    web: debug
