server:
  port: 8092

spring:
  application:
    name: core-service

eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://eureka:@eureka-service:8761/eureka

logging:
  level:
    web: DEBUG
    org.springframework.cloud.config: DEBUG
