server:
  port: ${PORT:${SERVER_PORT:0}}

spring:
  application:
    name: factura-sender-service

eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

logging:
  level:
    web: debug
