server:
  port: ${PORT:${SERVER_PORT:0}}

spring:
  application:
    name: factura-sender-service

eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://eureka:@eureka-service:8761/eureka

logging:
  level:
    web: DEBUG
    org.springframework.cloud.config: DEBUG
