server:
  port: ${PORT:${SERVER_PORT:0}}

spring:
  application:
    name: facturador-service

eureka:
  instance:
    hostname: eureka-service
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://${eureka.instance.hostname}:8761/eureka

logging:
  level:
    web: DEBUG
    org.springframework.cloud.config: DEBUG

resilience4j.circuitbreaker:
  instances:
    facturaSenderCircuitBreaker:
      registerHealthIndicator: true
      slidingWindowSize: 10
      permittedNumberOfCallsInHalfOpenState: 3
      slidingWindowType: TIME_BASED
      minimumNumberOfCalls: 4
      waitDurationInOpenState: 5s
      failureRateThreshold: 50
      eventConsumerBufferSize: 10
